### ISSUE TITLE
Extend cake so parameters can be passed to command.env()

### ISSUE THREAD

**Issue by s22h** [ticki/cake#3]
We need this for rustc (RUST_BACKTRACE) and cargo (CARGO_TARGET_DIR etc.) in bake.

**Comment by ticki** [comment]
Fixed by 
https://github.com/ticki/cake/commit/376dbe5d759e07d0585880f4670d0b7c4e5447b1

Note that `in "blah/blah/"` is now given _after_ the argument list. Environment variables can be specified with e.g.,

``` rust
cmd!("my", "command"; where BLAH = "var";  where OTHER = "var");
```
